language: scala
scala: 2.12.8
jdk: openjdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier/cache

env:
  global:
    - COURSIER_PROGRESS=0
    - SBT=./sbt
    # ENCRYPTION_PASSWORD
    - secure: "JjSj317n8p5Qi4f7OPI8BFY1fIfEIa09wFDo/czqmt7OLQg2mS+s8T0H3+OKnpgXZO9w2zj6t/+sVsqf7bM20+n+vb4FSxnAMEBTVio+JbggWGEvDucoiAfWVl944el7jNxA3hYME9GRI8XRvETW/nG7iVm4RJNAoHFUIrHG5/gPJzq8AqS5kO6GNwzQkCf1b1VK/2Cn2TGIyuu1BwgiJLkr/WHPRJNBCv+8xIz2xIyxq8d5OYsAF8b0FWN4HW+c673dW5J5vV6PlM/g6VaYISZaH+1OnrDhMPNgqHwyyNUb14fpmtoMrWOg3E//4grbku2pN5uJj3KVCZl5aftbkgsHF5X9yVKHRfEFsm1+yb2REYRaKgOKutXeqxW3gekoqK4Xhi1kGssxBkfs9wYxeHYcU8PC9gnfRjThtMqG7ko1FnMGv6S1R9GTf9N/DGogsOYqUxBgjnE/yTwGEl0I1IJc1zO4fX0TLgyJWU6LrBf+4Fz1tmZCy05LZX55NVvYdjYHFe3Es5fl5CeS9zOBA5tdjB6Ta81FTxFKvm13fBvLhu5pajOSMlTiLFXImHyQUH0+/ukfJQ0TJ4DwgC7kCR+aLwCPAgR7EfDEK5ZcRG7DeFTMbM16NmiSOn2E0eTtF9nbL7DFUKfo0/ACZuy0u/Ce7TN8V38Sj+kHo3V5Xjs="
    # GITHUB_TOKEN
    - secure: "doxPLw7zu0YV3DM2C+CxPaMoNsXIFj394otx+QuJsErxVk8DQGtKnO4Mr6fE2NsLls0/waeJi88KearOtK5UWljyWNgmaMHnTPE7GluCkYYrPc/bMzacUg+OAx2eDxcjow67uGLPJ9AR3GZikDS6SYy9oY0gs854iErj/fBeYl5Lzlh96ijPTOHaeIuV8hH9/t8q4obHO68win2b2Fsorq93YHtxE8I4b5IMheTq1mnL9MbyKQcs+YlPqmfJL/sqH4cPyNx9CHAmEaVj5qAgPwinaBF++cs0nIXCMtoOem5fh4mQNmAg3LtFZ9NyxOzhdxHShWGSxL7xSJC37JyGXdHIWR2zKoclnlSvqPrOF7Du759ZsXMRufrl/xqdzAy2KAn1Zmy0m9usuZwoYtk8HakyYvVR5LIH8fbtMfD/jMlR3tJhfbzvJM030bv97WQC85udBGoeL+dH3DMp/PX3oQo2/PFDVRz9CalniH5yPrGHkZ2uXuu+TqG/2cOpPLlnH2S9V1PYSWCzasxPKrExXxJVhhL7HN71f14YpuoLLdCrtX7vwhBKDuRTllSgWRItfO3wsmp7kW7mtQXmrV7H+8XBe2khf5oDKx+A1lKy4D70BTv5wVisZpp6lSTOiv/4Ih90QVbINv2XisL+Q/5W8oexa1BH01v0AJJ4QZa5/XE="
    # GITHUB_ACCESS_TOKEN
    - secure: "CQ7jmR3n5CdZT5dvAXLI8KOmmPB0P6mTZ67hGklrNiWzYICXwKJb4uwomjJU3cMV9pP9Vw1j/VfpvZQIIUlrVEr16hTHX7OpoFnvKmzfk2TXaLBoV3cwMq+UY+cZSVNpIl6ygxyP6LFqcAMU9ydVuX2Ng+7TP22YPbaIXEeFBoKOu3Hq10E3Fq0mpnNXDb+8pWmSernGiRVn0oxQydtVxh+ST2qEHUXMzUU5Bbpl98vZnnPODK7ZksxLLfYhg3gAlysCc6WxeumLlWWTP1L4NC49awq84mG+s4O8yOFQgUtCttidcv4VpAw0dB9bCVAXBRMxWPlNnCTAxvNQsA25AbTOD4L8hFtYWH53Z16E9dMoCpRdANemxtMrfZ833qShwMD8Mp0PawfMkqOCCZZ8212XHcSTTE/u9a2fx9eFudMKP+36qE1Fwd3PWm0OGSKup7JbF8ob3ItLvgyV01d1VonTateAnllA44UGH7Y4QROSDMVf6yemvqulIlUI8/JSVlF/9dhy1Rdgq/TXRsBzi1Ea2Plg0hux/OqGz+V9KZtOUFV16JQ9EZXdlDqBdU8McCvr+pMb3SdRfV4WFZ7NXz4sty3bVduoW8Xiy85X3UJavv7D2WLjmiNdHFnKK0+pMUgfh/Rj7Rp0Lj02/DeB8uOsZdKTE28VEopZk2Hc9Bw="
    # DISCORD_WEBHOOK_TOKENS
    - secure: "ip94khoy+1Fqem6u8bOoWc+Q4j9MI1F3kv/lwwmjs2NiTaV9OHEBcw/LoW7poXfn1R1fP4PMdjPKVWvd7bfaIZhjbPbUpPuw3H3EZ20qI5AZ8/lGZk592mCFuRs9TYOwl674b3kJa6SeCm/tiH/oGaZxTgfwe/yDRwIrwXc8nFphVtus6/V3ZT8G3lhmAVeXrhoHdCR8oWHPTh2/gk0RbcIfMePPKjz+PfJUx7KH8WJhkDCz2QF11814s91jdBt8Z/nVJc8s5DXLeIhQKFMEJTABG2KlJl0LWSWRCdPLkSMOO3Yd0hRIo/BPXGmoqE+eCpWADlsqTxFaJHhSZraSLqPka7Z1pJK2GayTPzamUArxavcqClk1uMmdNmhcIeBm6zjh2w2sJiVz13PR8uzp8ml6cXbxaJkYnveifN+6r51rpegYWyJx73z42cD3QCLr3r+dLn6+SK7SwLiKs9St3haYg74HyQ4qdi01jhNb3vdFVHfiE9fKw+YmqScCrmW2IHiHGn0tOWhSf1ZPmHGrY/5AqxGrVYAaheFG3QvYwFTqR1zwc6N3fz8rgq++irNbKQd6R/7EY+bwvH/4Or2uDG7tfWBd0l2CmKL1A2CvB3uZsrDRW9WIVXKxGvP/fpWaXyPVUmDYHK467roAIzh8GVlKpLdVwXtcoIZ2qgfp8BQ="

install:
  - mkdir scripts
  - $SBT transferCommonResources
  - scripts/commonSetup

script:
    - set -e

    - $SBT ++$TRAVIS_SCALA_VERSION test

    - |-
      if [ $TRAVIS_PULL_REQUEST == "false" ] && [[ "$TRAVIS_BRANCH" =~ backport/v.*|master ]]; then
        $SBT transferPublishAndTagResources;
        TRAVIS_JOB_NUMBER=1 scripts/publishAndTag 'slamdata/quasar-destination-s3';
      fi

after_success:
  - scripts/checkAndAutoMerge
  - scripts/discordTravisPost success https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

after_failure:
  - scripts/discordTravisPost failure https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

branches:
  only:
    - master
    - /^backport.*$/

before_cache:
  - find "$HOME/.sbt/" -name '*.lock' -print0 | xargs -0 rm
  - find "$HOME/.ivy2/" -name 'ivydata-*.properties' -print0 | xargs -0 rm
